name: .NET

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Setup .NET 6
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: 6.0.x
            -   name: Setup .NET 5
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: 5.0.x
            -   name: Restore dependencies
                run: dotnet restore
            -   name: Test
                run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput='./lcov.info' /p:ExcludeByAttribute="WebSocketDotNet.Utils.NoCoverageAttribute"
            -   name: Upload test coverage
                uses: coverallsapp/github-action@1.1.3
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    path-to-lcov: ./WebSocketDotNet.Tests/lcov.info
            -   name: Build
                run: dotnet build -c Release
            -   name: Upload NuGet Artifact
                uses: actions/upload-artifact@v2
                with:
                    name: WebSocketDotNet.nupkg
                    path: WebSocketDotNet/bin/Release/*.nupkg
            -   name: Upload to NuGet
                if: contains(github.event.head_commit.message, '[publish]') == true && github.event_name == 'push'
                run: dotnet nuget push ./WebSocketDotNet/bin/Release/*.nupkg -s ${{ secrets.NUGET_URL }} -k ${{ secrets.NUGET_API_KEY }}